### ISSUE TITLE
Property Reports - March 2016:  "Adelaide & SA" and "Melbourne & VIC" topic didn't jump (anchor) to its respective section.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#31]
URL: http://jenmanlive.emmixhosting.com.au/property-report-march-2016/

![image](https://cloud.githubusercontent.com/assets/12888048/19518602/a384b42e-963a-11e6-9708-c3c1d5a08963.png)
![image](https://cloud.githubusercontent.com/assets/12888048/19518603/a551221a-963a-11e6-8e83-dc3fe080ed72.png)

**Comment by emmixaustralia** [comment]
This is old, inherited content. When we took over the site it had ~300 posts/pages of content and I noticed many of them have issues like this. 

I need to talk to the project team / client to see who's responsibility it is to fix all of these issues, because going through all of their old content and checking their html skills wasn't part of the new site brief/budget.

**Comment by emmixaustralia** [comment]
Inherited content issue, closed.
